use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006009
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Cory
Watson
gphat
at
cpan
Karen
Etheridge
ether
Dave
Rolsky
autarch
Jesse
Luehrs
doy
Chris
Andrews
chrisandrews
lib
MooseX
UndefTolerant
ApplicationToClass
ApplicationToRole
Attribute
Class
Composite
Constructor
Role
